const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
  output: {
    path: path.join(__dirname, "/dist"), // Files will be sent here once they are bundled
    filename: "index_bundle.js", // name of the bundle generated by Webpack
  },
  // webpack 5 comes with devServer which loads in development mode
  devServer: {
    port: 3000,
    watchContentBase: true,
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/, // Specify for which file types, this loader should be used
        exclude: /node_modules/, // Do not compile node_modules, as they should be already compiled
        use: {
          loader: "babel-loader", // Use the babel-loader to compile the files
        },
      },
    ],
  },
  // Use src/index.html as the HTML entry point
  plugins: [new HtmlWebpackPlugin({ template: "./src/index.html" })],
};
